#
# oh-my-zsh configuration
#

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Choose zsh theme
ZSH_THEME="agnoster"

# Don't display username in prompt on personal computer
export DEFAULT_USER=`whoami`

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Add zsh plugins integrations
plugins=(git osx zsh-autosuggestions docker)

source $ZSH/oh-my-zsh.sh

#
# User configuration
#

# Import common configuration
source $HOME/.dotfiles/shell/common_config

# Import machine local configuration
if [[ -f $HOME/.zshrc.local ]]; then
  source $HOME/.zshrc.local
fi

#
# zsh specific config
#
