###############################################################################
### OH-MY-ZSH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Plugins from ~/.oh-my-zsh/custom/plugins/
plugins=(git brew osx rake tmux)

source $ZSH/oh-my-zsh.sh

###############################################################################
### ADDITIONAL CONFIG

# Import common configuration
source ~/.dotfiles/common/common_config

# Aliases
source ~/.dotfiles/zsh/aliases.zsh

# Import machine local configuration
if [[ -f ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi

# Only display username if not on laptop
export DEFAULT_USER=`whoami`

# TODO: To add in config.local on lab machines @Imperial
#export PATH="/usr/local/maple/bin:/vol/lab/satsolvers/bin:/vol/lab/secondyear/bin:/vol/lab/bin:/vol/lab/bin/Linux/amd64:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/games:/vol/lab/secondyear/bin:/vol/lab/bin:/vol/lab/bin/Linux/x86_64:/vol/lab/satsolvers/bin/"

# TODO: To add in config.local on mac
# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PATH="$PYENV_ROOT/bin:$PATH"
[ -d "$PYENV_ROOT" ] && eval "$(pyenv init -)"
alias pyenv_install="CFLAGS=-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include pyenv install"
alias pyenv_venv="eval \"\$(pyenv virtualenv-init -)\""

