#!/usr/bin/env bash

###############################################################################
### BASH-IT

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=false

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

###############################################################################
### ADDITIONAL CONFIG

# Import common configuration
source $HOME/.dotfiles/common/common_config

# Aliases
source $HOME/.dotfiles/bash/aliases.bash

# Import machine local configuration
if [[ -f $HOME/.bash_profile.local ]]; then
  source $HOME/.bash_profile.local
fi


# Docker
alias docker_init="eval \"\$(docker-machine env default)\""


